version: "3.9"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: iprwc
    volumes:
      - iprwc_data:/var/lib/mysql
    ports:
      - 6033:3306

volumes:
  iprwc_data:
